- alias: preview-redis
  name: jx-micronaut-seed-redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 6.1.0

  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: jx-micronaut-seed
  repository: file://../jx-micronaut-seed
